name: Build and Publish Docker Images to ECR

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Amazon ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # Build and push frontend image
      - name: Build and push frontend image
        env:
          ECR_REGISTRY: 124292275967.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_TAG: posecraft_fe-image:${{ github.sha }}
        run: |
          docker build -t posecraft_fe-image -f posecraft/Dockerfile posecraft/
          docker tag posecraft_fe-image ${ECR_REGISTRY}/${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${IMAGE_TAG}

      # Build and push backend image
      - name: Build and push backend image
        env:
          ECR_REGISTRY: 124292275967.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_TAG: posecraft_be-image:${{ github.sha }}
        run: |
          docker build -t posecraft_be-image -f server/Dockerfile server/
          docker tag posecraft_be-image ${ECR_REGISTRY}/${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${IMAGE_TAG}

      # Build and push worker image
      - name: Build and push worker image
        env:
          ECR_REGISTRY: 124292275967.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_TAG: posecraft_worker-image:${{ github.sha }}
        run: |
          docker build -t posecraft_worker-image -f server/worker.Dockerfile server/
          docker tag posecraft_worker-image ${ECR_REGISTRY}/${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${IMAGE_TAG}

      # Optionally, deploy Docker Compose stack
      # Uncomment these steps if you want to deploy the stack after pushing images
      #- name: Deploy Docker Compose stack
      #  run: |
      #    docker-compose -f docker-compose.yml up -d


